### ISSUE TITLE
Mypage 의 Ui 를 구현하겠습니다.

### ISSUE THREAD

**Issue by kimjeakwan** [Team-MindWay/Dormitory-Manager-Android#4]
## 📌 개요
- 할 일을 간단하게 적어주세요.
Mypage 의 Ui 를 구현하겠습니다.

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들
- 참고할 사항이 있다면 적어주세요.

**Comment by nahyunuk** [comment]
확인 했습니다
